# Generated by Django 2.1.3 on 2018-11-26 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_guias', 'altera_tabela_controle_registros_cria_ultima_verificacao_002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='ponto',
            new_name='geom',
        ),
    ]
