# Generated by Django 2.1.3 on 2018-11-26 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_guias', '0001_auto_20181126_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destino',
            new_name='Atrativo',
        ),
    ]
