# Generated by Django 2.1.3 on 2018-11-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_guias', 'cria_tabela_controle_ultima_verificacao_registros'),
        ('catalogo_guias', 'altera_tabela_controle_registros_001'),
    ]

    operations = [
    ]
