# Generated by Django 2.1.3 on 2018-11-27 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_guias', '0002_auto_20181126_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa_fisica',
            name='usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoa_juridica',
            name='usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
