# Generated by Django 2.1.3 on 2018-11-27 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_guias', '0003_auto_20181127_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa_fisica',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pessoa_juridica',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_cliente',
            field=models.BooleanField(default=False, verbose_name='cliente status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_guia',
            field=models.BooleanField(default=False, verbose_name='guia status'),
        ),
        migrations.AlterField(
            model_name='pessoa_fisica',
            name='usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoa_juridica',
            name='usuario',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
