# Generated by Django 2.1.3 on 2018-11-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_guias', '0004_auto_20181127_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrativo',
            name='guias',
            field=models.ManyToManyField(to='catalogo_guias.Pessoa_Juridica'),
        ),
    ]
